config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  resources :postcodes

  resources :lsoas

  get :service, to: 'service#index'

  get :check, to: 'service#check'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lsoa.rb
class Lsoa < ApplicationRecord
	validates :value, presence: true, uniqueness: true,
                   length: { minimum: 5, maximum: 25 }

  validates :description, presence: true,
                   length: { maximum: 50 }

	before_save :modify_string_case

	def modify_string_case
		self.value.downcase!
	end      
end

app/models/postcode.rb
class Postcode < ApplicationRecord
  include PostcodeUtils

	validates :code, presence: true, uniqueness: true, length: { minimum: 6, maximum: 8 }

  validates :description, presence: true, length: { maximum: 50 }

  validate :validate_postcode

  before_save :modify_string_case

  def modify_string_case
    self.code.upcase!
  end

	def validate_postcode
		if !is_valid_postcode?(self.code)
			errors.add(:code, ': Invalid UK postcode')
		end
	end        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lsoas_controller.rb
class LsoasController < ApplicationController
	def index
    @lsoas = Lsoa.all
  end

	def show
    @lsoa = Lsoa.find(params[:id])
  end

  def new
    @lsoa = Lsoa.new
  end
 
	def create
		@lsoa = Lsoa.new(lsoa_params)

    if @lsoa.save
		  redirect_to @lsoa
    else 
      render 'new'
    end
	end

  def edit
    @lsoa = Lsoa.find(params[:id])
  end

  def update
    @lsoa = Lsoa.find(params[:id])

    if @lsoa.update(lsoa_params)
      redirect_to @lsoa
    else 
      render 'edit'
    end
  end

  def destroy
    @lsoa = Lsoa.find(params[:id])
    
    @lsoa.destroy

    redirect_to lsoas_path 
  end

private
  def lsoa_params
    params.require(:lsoa).permit(:value, :description)
  end
end

app/controllers/postcodes_controller.rb
class PostcodesController < ApplicationController
	def index
    @postcodes = Postcode.all
  end

	def show
    @postcode = Postcode.find(params[:id])
  end

  def new
    @postcode = Postcode.new
  end
 
	def create
		@postcode = Postcode.new(postcode_params)

    if @postcode.save
		  redirect_to @postcode
    else 
      render 'new'
    end
	end

  def edit
    @postcode = Postcode.find(params[:id])
  end

  def update
    @postcode = Postcode.find(params[:id])

    if @postcode.update(postcode_params)
      redirect_to @postcode
    else 
      render 'edit'
    end
  end

  def destroy
    @postcode = Postcode.find(params[:id])
    
    @postcode.destroy

    redirect_to postcodes_path 
  end

private
  def postcode_params
    params.require(:postcode).permit(:code, :description)
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  include PostcodeUtils

	def index
    @pcode = nil
    @result = nil
    @error = nil
	end

  def check
    @result = false
    @pcode = params[:pcode] || ''
    if !is_valid_postcode?(@pcode )
      @error = 'Please enter a valid UK postcode'
    else
      @result = can_serve_postcode?(@pcode)
    end
    render 'index'
  end

 private

  def is_whitelisted_lsoa?(lsoa_value)
    Lsoa.all.each do | lo |
      if lsoa_value.start_with?(lo.value)
        return true
      end
    end
    return false
  end

  def is_whitelisted_postcode?(postcode_value)
    result = Postcode.where(:code => postcode_value)
    return !result.empty?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postcodes_helper.rb
module PostcodesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sh24</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lsoas/_form.html.erb
<%= form_with(model: @lsoa, local: true) do |form| %>

<% if @lsoa.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@lsoa.errors.count, "error") %> prohibited this lsoa from being saved:
    </h2>
    <ul>
      <% @lsoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label :value %><br>
  <%= form.text_field :value %>
</p>

<p>
  <%= form.label :description %><br>
  <%= form.text_area :description %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

<%= link_to 'Back', lsoas_path %>

app/views/lsoas/edit.html.erb
<h1>Edit White-listed Lsoa</h1>
  
<%= render 'form' %>

app/views/lsoas/index.html.erb
<h1>All White-list Lsoas</h1>

<%= link_to 'Add Lsoa', new_lsoa_path %>
<br>
<br>
 
<% if @lsoas.length > 0 %>
  <table>
    <tr>
      <th>Value</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
   
    <% @lsoas.each do |lsoa| %>
      <tr>
        <td><%= lsoa.value %>, </td>
        <td><%= lsoa.description %></td>
        <td>(<%= link_to 'Show', lsoa_path(lsoa) %>,</td>
        <td><%= link_to 'Edit', edit_lsoa_path(lsoa) %>,</td>
        <td><%= link_to 'Delete', lsoa_path(lsoa),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>)
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

<br>
<%= link_to 'Home', welcome_index_path %> 

app/views/lsoas/new.html.erb
<h1>New White-listed Lsoa</h1>

<BR>
<b>Suggested Examples:</b>
<p>southwark</p>
<p>lambeth</p>
<BR>

<%= render 'form' %>

app/views/lsoas/show.html.erb
<h1>Show White-listed Lsoa</h1>

<p>
  <strong>Value:</strong>
  <%= @lsoa.value %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @lsoa.description %>
</p>

<%= link_to 'Edit', edit_lsoa_path(@lsoa) %> |
<%= link_to 'All White-list Lsoas', controller: 'lsoas' %>

app/views/postcodes/_form.html.erb
<%= form_with(model: @postcode, local: true) do |form| %>

<% if @postcode.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@postcode.errors.count, "error") %> prohibited this postcode from being saved:
    </h2>
    <ul>
      <% @postcode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label :code %><br>
  <%= form.text_field :code %>
</p>

<p>
  <%= form.label :description %><br>
  <%= form.text_area :description %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

<%= link_to 'Back', postcodes_path %>

app/views/postcodes/edit.html.erb
<h1>Edit White-listed Postcode</h1>
  
<%= render 'form' %>

app/views/postcodes/index.html.erb
<h1>All White-list Postcodes</h1>

<%= link_to 'Add Postcode', new_postcode_path %>
<br>
<br>
 
<% if @postcodes.length > 0 %>
  <table>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
   
    <% @postcodes.each do |postcode| %>
      <tr>
        <td><%= postcode.code %>, </td>
        <td><%= postcode.description %></td>
        <td>(<%= link_to 'Show', postcode_path(postcode) %>,</td>
        <td><%= link_to 'Edit', edit_postcode_path(postcode) %>,</td>
        <td><%= link_to 'Delete', postcode_path(postcode),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>)
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

<br>
<%= link_to 'Home', welcome_index_path %> 

app/views/postcodes/new.html.erb
<h1>New White-listed Postcode</h1>

<BR>
<b>Suggested Examples:</b>
<p>SH24 1AA</p>
<p>SH24 1AB</p>
<BR>

<%= render 'form' %>

app/views/postcodes/show.html.erb
<h1>Show White-listed Postcode</h1>

<p>
  <strong>Code:</strong>
  <%= @postcode.code %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @postcode.description %>
</p>

<%= link_to 'Edit', edit_postcode_path(@postcode) %> |
<%= link_to 'All White-list Postcodes', controller: 'postcodes' %>

app/views/service/index.html.erb
<h1>Postcode Service Status</h1>

<form action="check" method="get" id='postcodes-form'>

<div>
	<p>Please enter a valid UK postcode:</p>
	<input type="text" name="pcode" value="<%= @pcode %>" placeholder="UK postcode">
</div>
<div class="">
	<button type="submit" id='service-check'>Check</button>
	<br/>
</div>
<br>

<% if !@pcode.blank? %>
	Result: <%= @result %>
<% end %>
<br>

<% if !@error.blank? %>
	Error: <%= @error %>
<% end %>
<br>

<br>
<%= link_to 'Home', welcome_index_path %> 

app/views/welcome/index.html.erb
<h1>SH24 Code Challenge</h1>

<h4>Backend Part: Postcode Service Checker System</h4>
1. Please use the service from here:<br> 
<br><%= link_to 'Postcode Service Checker', controller: 'service' %><br>
<br>

2. To configure the service:<br>
<br><%= link_to 'Manage White-list Lsoas', controller: 'lsoas' %><br>
<br><%= link_to 'Manage White-list Postcodes', controller: 'postcodes' %><br>

<h4>Frontend Part: Progress Bar with Steps</h4>
<p>Please click on Next or Prev to change the progress.</p>
<div class="container">	
	<div class="wrapper">	
		<div class="arrow-steps clearfix">
			<div class="step current"> <span>AGE + POSTCODE</span> </div>
			<div class="step"> <span>ABOUT YOU</span> </div>
			<div class="step"> <span>YOUR KIT</span> </div>
			<div class="step"> <span>CONTACT + DELIVERY</span> </div>
			<div class="step"> <span>MORE ABOUT YOU</span> </div>
			<div class="step"> <span>CONFIRM + PAY</span> </div>
		</div>
		<div class="nav clearfix">
			<a href="#" class="prev">Previous</a>
			<a href="#" class="next pull-right">Next</a>
		</div>
	</div>
</div>